/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Giocatore.*;
import org.example.Tracciato.*;

import java.util.Random;


public class Main {
    public static void main(String[] args) {
        try {
            // Caricamento del tracciato
            CaricamentoTracciato caricamento = new CaricamentoTracciatoFile();
            Tracciato tracciato = caricamento.caricaTracciato("src/main/resources/Configurazione_Tracciato.txt");
            tracciato.stampaTracciato();

            Random random = new Random();
            // Posizioni di partenza possibili
            int[] posizione1 = {1, 1};
            int[] posizione2 = {1, 2};

            //Decisione casuale di chi ha una miglior partenza
            if (random.nextBoolean()) {
                Giocatore bot1 = new Bot1("Bot1", posizione1, tracciato);
                Giocatore bot2 = new Bot2("Bot2", posizione2, tracciato);
                eseguiGara(bot1, bot2, tracciato);
            } else {
                Giocatore bot1 = new Bot1("Bot1", posizione2, tracciato);
                Giocatore bot2 = new Bot2("Bot2", posizione1, tracciato);
                eseguiGara(bot1, bot2, tracciato);
            }
        } catch (Exception e) {
            System.err.println("Errore: " + e.getMessage());
        }
    }


    private static void eseguiGara(Giocatore bot1, Giocatore bot2, Tracciato tracciato) {
        int turno = 1;
        while (true) {
            System.out.println("\nTurno " + turno);
            bot1.muovi();
            bot2.muovi();

            // Stampa delle posizioni dei bot
            System.out.println(bot1.getNome() + " posizione: " +
                    bot1.getPosizione()[0] + "," + bot1.getPosizione()[1]);
            System.out.println(bot2.getNome() + " posizione: " +
                    bot2.getPosizione()[0] + "," + bot2.getPosizione()[1]);

            // Controllo se uno dei bot ha raggiunto il traguardo
            if (tracciato.isArrivato(bot1.getPosizione())) {
                System.out.println(bot1.getNome() + " ha raggiunto il traguardo! Vince la gara!");
                break;
            }
            if (tracciato.isArrivato(bot2.getPosizione())) {
                System.out.println(bot2.getNome() + " ha raggiunto il traguardo! Vince la gara!");
                break;
            }

            turno++;
        }
    }
}
